services:
  - name: Updated_plant_model
    type: web
    env: python=3.11
    buildCommand: pip install -r requirements.txt
    startcommand: uvicorn Updated_plant_model:app --host 0.0.0.0 --port $PORT
